;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        beginning-of-defun
        c-electric-delete-forward
        comint-delchar-or-maybe-eof
        end-of-buffer
        end-of-defun
        forward-sexp
        indent-for-tab-command
        kill-region
        magit-discard-item
        magit-stage-item
        ns-copy-including-secondary
        prelude-move-beginning-of-line
        prelude-top-join-line
        python-indent-electric-colon
        scroll-other-window
        smex
        sp--self-insert-command
        sp-backward-delete-char
        sp-backward-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-remove-active-pair-overlay
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        magit-status
        ))
