;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        beginning-of-defun
        c-electric-delete-forward
        comint-delchar-or-maybe-eof
        electric-newline-and-maybe-indent
        end-of-buffer
        end-of-defun
        forward-sentence
        forward-sexp
        god-mode-self-insert
        indent-for-tab-command
        kill-region
        magit-discard-item
        magit-stage-item
        ns-copy-including-secondary
        org-self-insert-command
        prelude-move-beginning-of-line
        prelude-top-join-line
        puppet-interpolate
        python-indent-electric-colon
        scroll-other-window
        slime-autodoc-space
        slime-indent-and-complete-symbol
        smex
        sp--self-insert-command
        sp-backward-delete-char
        sp-backward-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-remove-active-pair-overlay
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        isearch-backward-regexp
        magit-status
        ))
