;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        beginning-of-defun
        c-electric-brace
        c-electric-delete-forward
        c-electric-semi&comma
        comint-delchar-or-maybe-eof
        downcase-region
        electric-newline-and-maybe-indent
        end-of-buffer
        end-of-defun
        eval-print-last-sexp
        forward-sentence
        forward-sexp
        go-mode-insert-and-indent
        god-mode-self-insert
        haskell-indentation-delete-backward-char
        ibuffer-mark-for-delete
        indent-for-tab-command
        kill-region
        magit-discard-item
        magit-stage-item
        magit-unstage-item
        ns-copy-including-secondary
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-todo
        prelude-move-beginning-of-line
        prelude-top-join-line
        puppet-interpolate
        python-indent-electric-colon
        scroll-other-window
        slime-autodoc-space
        slime-indent-and-complete-symbol
        smex
        sp--self-insert-command
        sp-backward-delete-char
        sp-backward-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-kill-word
        sp-remove-active-pair-overlay
        sp-splice-sexp
        toggle-comment-region
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        ido-switch-buffer
        isearch-backward-regexp
        magit-status
        ))
